/**
 * Placeholder cast for demos only — `npm run demo:seed` writes these into `characters`
 * and `npm run demo:clear` takes them out again (matched by name). They are not the
 * real mystery: nothing here settles what happened in 1924 or who dies in 1926 beyond
 * the one demo murderer/victim pair staff see on /admin.
 */
export type DemoCharacter = {
  characterName: string;
  occupation: string;
  publicBiography: string;
  factions: string[];
  privateBiography: string;
  secrets: string[];
  objectives: string[];
  murderer?: boolean;
  victim?: boolean;
};

export const demoCharacters: DemoCharacter[] = [
  {
    characterName: "Vivienne Marlowe",
    occupation: "Society columnist, Manchester Union",
    publicBiography: "Her Sunday column decides who was seen and who was merely present. She has attended every opening on Elm Street since 1919.",
    factions: ["The Press", "Elm Street Society"],
    privateBiography: "Vivienne wrote the 1924 item that first called the masquerade 'a terror'. Her editor cut half of it. She kept the other half.",
    secrets: ["You hold the unprinted half of your 1924 column, naming who left by the river side.", "You owe Silas Brennan four hundred dollars."],
    objectives: ["Learn who sent the black envelopes before the night is out.", "Keep your unprinted column from being read aloud."],
  },
  {
    characterName: "Silas Brennan",
    occupation: "Importer of 'medicinal tonics'",
    publicBiography: "A cheerful man with a warehouse by the Merrimack and a great many friends on the police payroll.",
    factions: ["The River Trade"],
    privateBiography: "Silas supplied The Black Veil from the night it opened. When it closed he lost his best customer and gained a debt he cannot explain.",
    secrets: ["Your crates still come in through the river door.", "Someone has been skimming your shipments since 1924."],
    objectives: ["Find out who is skimming your shipments.", "Collect what Vivienne Marlowe owes you, discreetly."],
    murderer: true,
  },
  {
    characterName: "Augustine Pell",
    occupation: "Heir to a mill fortune",
    publicBiography: "Third-generation Amoskeag money. Plays the piano badly and loudly, and buys rounds for the room.",
    factions: ["Mill Families", "Elm Street Society"],
    privateBiography: "Augustine's father broke the 1922 strike. Augustine has spent four years trying to buy back the town's good opinion.",
    secrets: ["You signed the 1922 eviction notices yourself.", "You are nearly bankrupt."],
    objectives: ["Secure a loan from someone in this room.", "Keep the eviction notices out of the conversation."],
    victim: true,
  },
  {
    characterName: "Sergeant Thomas Halloran",
    occupation: "Manchester Police, West Side precinct",
    publicBiography: "He was first through the door in 1924, or so his report says. He has been passed over for promotion twice since.",
    factions: ["The Law"],
    privateBiography: "Halloran's report of the 1924 raid was rewritten before it was filed. He knows by whom.",
    secrets: ["You took money to arrive late in 1924.", "You kept the original raid report."],
    objectives: ["Learn who is paying the precinct now.", "Leave tonight with a name you can arrest."],
  },
  {
    characterName: "Lena Duquette",
    occupation: "Jazz singer",
    publicBiography: "Billed in Boston as 'the Merrimack Nightingale'. She sang at the Black Veil the year it opened and has never said why she stopped.",
    factions: ["The Orchestra"],
    privateBiography: "Lena was on stage at 11:47 on the night of the masquerade. The music did not stop when the papers say it did.",
    secrets: ["You saw who opened the river door in 1924.", "You are travelling under a name that is not yours."],
    objectives: ["Find the person who wrote you an anonymous letter last week.", "Sing one song before midnight."],
  },
  {
    characterName: "Dr. Ambrose Whitcombe",
    occupation: "Physician, Elliot Hospital",
    publicBiography: "Respected, discreet, and much in demand on evenings when someone has had too much of Silas Brennan's tonic.",
    factions: ["Elm Street Society"],
    privateBiography: "Whitcombe signed a death certificate in November 1924 without seeing the body.",
    secrets: ["You signed a certificate you should not have.", "You prescribe more than tonics."],
    objectives: ["Find out who knows about the 1924 certificate.", "Leave before anyone needs a doctor."],
  },
  {
    characterName: "Rosalind Fairweather",
    occupation: "Suffragist and schoolteacher",
    publicBiography: "Organised the mill girls' reading circle and does not care who knows it.",
    factions: ["Mill Workers"],
    privateBiography: "Rosalind has been quietly collecting evidence of the mill families' payments to the police.",
    secrets: ["You have a ledger page from the mill accounts.", "You were at the 1924 masquerade under a borrowed mask."],
    objectives: ["Get a police officer to admit the payments in front of a witness.", "Protect your source in the counting-house."],
  },
  {
    characterName: "Jack 'Lucky' Moreau",
    occupation: "Card sharp",
    publicBiography: "Never seems to work and never seems short of money. Excellent company until the cards come out.",
    factions: ["The River Trade"],
    privateBiography: "Jack won a share of the Black Veil's lease in a card game in 1923 and has never been able to collect.",
    secrets: ["You own a share of the building.", "Your luck is a marked deck."],
    objectives: ["Find the lease papers.", "Win back what you lost to Augustine Pell."],
  },
  {
    characterName: "Constance Abernathy",
    occupation: "Widow of a state senator",
    publicBiography: "Hosts the best Sunday luncheons in Hillsborough County and remembers every slight since 1898.",
    factions: ["Elm Street Society", "Mill Families"],
    privateBiography: "Constance's late husband was the club's silent protector at the State House.",
    secrets: ["Your husband's letters mention the club by name.", "You are not as rich as your luncheons suggest."],
    objectives: ["Recover your husband's letters before anyone reads them.", "Arrange a match for your nephew."],
  },
  {
    characterName: "Eamon Kilbride",
    occupation: "Bartender",
    publicBiography: "Poured drinks at the Black Veil from 1921 until the doors closed. Says nothing about it, pleasantly.",
    factions: ["House Staff"],
    privateBiography: "Eamon kept the house keys after the closure. Nobody ever asked for them back.",
    secrets: ["You still have the keys to the cellar.", "You know where Cassandra kept her ledger."],
    objectives: ["Decide whom you trust with the cellar keys.", "Make sure no one drinks from the green bottle."],
  },
  {
    characterName: "Marguerite Leclair",
    occupation: "Milliner, Elm Street",
    publicBiography: "Swears the club's door opened onto her own alley. She sells the best hats in Manchester and hears everything.",
    factions: ["Elm Street Society"],
    privateBiography: "Marguerite rented her back room to the club for deliveries, for cash, no questions asked.",
    secrets: ["The alley door was yours.", "You have a hatbox you have never opened."],
    objectives: ["Find out what is in the hatbox before anyone else does.", "Sell three hats tonight."],
  },
  {
    characterName: "Professor Linus Okonkwo",
    occupation: "Lecturer in chemistry, Saint Anselm College",
    publicBiography: "Lectures on industrial dyes, consults for the mills, and has an unsettling knowledge of poisons.",
    factions: ["Mill Families"],
    privateBiography: "The mills paid Linus to analyse a tonic that made three workers ill in 1925.",
    secrets: ["You know Silas Brennan's tonic is cut with something dangerous.", "Your report was never published."],
    objectives: ["Get a sample from tonight's bar.", "Warn someone without being seen to warn them."],
  },
  {
    characterName: "Beatrice 'Bea' Calloway",
    occupation: "Telephone exchange operator",
    publicBiography: "Connects half the calls in Manchester and claims to listen to none of them.",
    factions: ["Mill Workers"],
    privateBiography: "Bea placed a call to the police at 11:52 on the night of the masquerade. It was never logged.",
    secrets: ["You remember who asked for the police that night.", "You listen to every call."],
    objectives: ["Sell what you heard to the highest bidder.", "Keep your job."],
  },
  {
    characterName: "Gideon Ashcroft",
    occupation: "Attorney",
    publicBiography: "Represents the mill families, the diocese, and at least one person he will not name.",
    factions: ["Mill Families", "The Law"],
    privateBiography: "Gideon drew up the Black Veil's lease, and the second, secret one that followed it.",
    secrets: ["There are two leases for the building.", "Your unnamed client is in this room."],
    objectives: ["Keep both leases out of sight.", "Find out who sent your client an envelope."],
  },
  {
    characterName: "Odette Vance",
    occupation: "Cigarette girl",
    publicBiography: "Works the room with a tray and a smile, and remembers which guests tip in silver.",
    factions: ["House Staff"],
    privateBiography: "Odette was hired last week by someone she has never met, paid in advance.",
    secrets: ["You were told to watch one guest and report at midnight.", "Your tray has a false bottom."],
    objectives: ["Learn who hired you.", "Deliver the folded note in your tray to the right person."],
  },
  {
    characterName: "Harold Pemberton",
    occupation: "Boston & Maine stationmaster",
    publicBiography: "Knows every train in and out of Manchester and who was on it.",
    factions: ["The River Trade"],
    privateBiography: "Harold sold a one-way ticket on November 1, 1924, to a veiled woman who paid in gold.",
    secrets: ["You remember the woman's face.", "You keep a second ticket book."],
    objectives: ["Find out if the veiled woman has come back.", "Keep your second ticket book quiet."],
  },
  {
    characterName: "Ines Castellano",
    occupation: "Dressmaker",
    publicBiography: "Sews half the gowns in the room tonight, and knows whose were paid for and whose were not.",
    factions: ["Mill Workers", "Elm Street Society"],
    privateBiography: "Ines made the gown Cassandra wore at the 1924 masquerade, and a second identical one for someone else.",
    secrets: ["There were two identical gowns.", "You know who ordered the second."],
    objectives: ["Discover who is wearing a gown you made in 1924.", "Collect your unpaid bills."],
  },
  {
    characterName: "Father Declan Rourke",
    occupation: "Curate, Saint Anne's",
    publicBiography: "Condemns the speakeasies from the pulpit on Sunday and is seen near them on Saturday.",
    factions: ["The Church"],
    privateBiography: "Declan heard a confession in November 1924 that he cannot repeat and cannot forget.",
    secrets: ["You know what happened at the masquerade from a confession.", "You enjoy a drink more than you should."],
    objectives: ["Persuade the person who confessed to come forward.", "Avoid being photographed."],
  },
  {
    characterName: "Clara Whitlock",
    occupation: "Aviator and motorist",
    publicBiography: "Drove from Boston in an hour and forty minutes and wants everyone to know it.",
    factions: ["Elm Street Society"],
    privateBiography: "Clara runs messages for the River Trade in her roadster. Nobody stops a society girl.",
    secrets: ["Your roadster carries more than luggage.", "You are engaged to someone in this room, secretly."],
    objectives: ["Make a delivery to the cellar before midnight.", "Keep the engagement secret until the toast."],
  },
  {
    characterName: "Mortimer Graves",
    occupation: "Undertaker",
    publicBiography: "Courteous, punctual, and somehow always present when he is needed.",
    factions: ["The Church"],
    privateBiography: "Mortimer buried an empty coffin in 1924 and was paid well to forget it.",
    secrets: ["The 1924 coffin was empty.", "You know who paid for it."],
    objectives: ["Learn whether the person you didn't bury is alive.", "Find a new client before the night ends."],
  },
  {
    characterName: "Pearl Hastings",
    occupation: "Photographer, Manchester Leader",
    publicBiography: "Took the last known photograph of the 1924 masquerade. The negative was never found.",
    factions: ["The Press"],
    privateBiography: "Pearl did keep the negative. It shows one more face than the print.",
    secrets: ["You have the missing negative.", "The extra face in it is someone here tonight."],
    objectives: ["Photograph everyone at the party.", "Match tonight's faces against your negative."],
  },
  {
    characterName: "Walter Sinclair",
    occupation: "Amoskeag counting-house clerk",
    publicBiography: "Neat, nervous, and very good with figures. Placed the club's door 'hard by the mill gates'.",
    factions: ["Mill Workers"],
    privateBiography: "Walter has been altering the mill's books to cover payments he was ordered to make.",
    secrets: ["You altered the mill accounts.", "Rosalind Fairweather has one of your ledger pages."],
    objectives: ["Get your ledger page back.", "Find out who ordered the payments in the first place."],
  },
  {
    characterName: "Sylvie Montague",
    occupation: "Dance instructor",
    publicBiography: "Taught half of Elm Street the Charleston and will teach the other half tonight.",
    factions: ["The Orchestra"],
    privateBiography: "Sylvie has been writing to Cassandra Castello for two years. The letters come back unopened.",
    secrets: ["You know an address for Cassandra.", "You have been paid to keep it."],
    objectives: ["Learn whether Cassandra is in Manchester.", "Get everyone on the dance floor at midnight."],
  },
  {
    characterName: "Reginald Thorne",
    occupation: "Real-estate speculator",
    publicBiography: "Buying up the mill district one empty building at a time. Would very much like the Black Veil's.",
    factions: ["Mill Families"],
    privateBiography: "Reginald needs the club's building to close a deal that will ruin three families in this room.",
    secrets: ["Your deal depends on owning the building by Monday.", "You forged a signature on the deed transfer."],
    objectives: ["Acquire the lease from whoever holds it.", "Keep Gideon Ashcroft from seeing the forged deed."],
  },
];
